syntax = "proto3";
import "digital.proto";

package digital;

option go_package = "./proto";

service AuthService {
    rpc Health (HealthRequest) returns (HealthReply) {}
    rpc Login (LoginRequest) returns (Tokens) {}
    rpc Refresh (Tokens) returns (Tokens) {}
    rpc ValidateToken(Tokens) returns (User) {}
    rpc Register (CreateUserRequest) returns (StatusReply) {}
    rpc GetUsers (UsersRequest) returns (Users) {}
    rpc GetUser (StringIDRequest) returns (User) {}
    rpc CreateUser (CreateUserRequest) returns (User) {}
    rpc UpdateUser (CreateUserRequest) returns (StatusReply) {}
    rpc DeleteUser (StringIDRequest) returns (StatusReply) {}
}

message LoginRequest {
    string login = 1;
    string password = 2;
}

message Tokens {
    string accessToken = 1;
    string refreshToken = 2;
}

message UsersRequest {
    uint32 page = 1;
    uint32 limit = 2;
}

message Users {
    repeated User users = 1;
    Pagination pagination = 2;
}

message CreateUserRequest {
    string name = 1;
    string lastname = 2;
    string login = 3;
    string email = 4;
    string phone = 5;
    string password = 6;
}