syntax = "proto3";
package digital;
option go_package = "./proto";

enum Status {
    UNKNOWN = 0;
    ACTIVE = 1;
    INACTIVE = 2;
    OK = 3;
    ERROR = 4;
}

message StatusReply {
    Status status = 1; 
}

message HealthRequest {
    string ping = 1;
}

message HealthReply {
    string ping = 1;
}

message StringIDRequest {
    string id = 1;
}

message Pagination {
    uint32 page = 1;
    uint32 pages = 2;
    uint32 limit = 3;
    uint32 total = 4;
}

message User {
    uint64 id = 1;
    string name = 2;
    string lastname = 3;
    string login = 4;
    string email = 5;
    bool emailVerify = 6;
    int64 phone = 7;
    bool phoneVerify = 8;
    bool active = 9;
    string createdAt = 10;
    string updatedAt = 11;
}